import type { McpConnection } from '@/lib/types';

export type McpCatalogCategory =
  | 'core'
  | 'code'
  | 'web'
  | 'data'
  | 'productivity'
  | 'ops'
  | 'commerce'
  | 'sandbox';

export interface McpCatalogItem {
  id: string;
  name: string;
  category: McpCatalogCategory;
  transport: McpConnection['transport'];
  endpoint: string;
  summary: string;
  authLabel: string;
  secretLabel?: string;
  secretPlaceholder?: string;
  setupHint: string;
  tools: string[];
  tags: string[];
  approval: string;
}

export const MCP_CATALOG_FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'core', label: 'Core' },
  { id: 'code', label: 'Code' },
  { id: 'web', label: 'Web' },
  { id: 'data', label: 'Data' },
  { id: 'productivity', label: 'Work' },
  { id: 'ops', label: 'Ops' },
  { id: 'commerce', label: 'Money' },
  { id: 'sandbox', label: 'Sandbox' },
] satisfies Array<{ id: 'all' | McpCatalogCategory; label: string }>;

export const MCP_CATALOG = [
  {
    id: 'filesystem',
    name: 'Filesystem MCP',
    category: 'core',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-filesystem /workspace',
    summary: 'Scoped file reads and writes for project-aware agents.',
    authLabel: 'local path',
    setupHint: 'Limit the command to the smallest workspace path the agent needs.',
    tools: ['read_file', 'write_file', 'list_directory'],
    tags: ['files', 'local'],
    approval: 'L1 writes',
  },
  {
    id: 'fetch',
    name: 'Fetch MCP',
    category: 'core',
    transport: 'stdio',
    endpoint: 'uvx mcp-server-fetch',
    summary: 'Fetch web pages and convert content into LLM-friendly context.',
    authLabel: 'no token',
    setupHint: 'Use for documentation and URL reading; pair with approvals for data extraction.',
    tools: ['fetch', 'read_url', 'convert_html'],
    tags: ['web', 'docs'],
    approval: 'L0 read',
  },
  {
    id: 'memory',
    name: 'Memory MCP',
    category: 'core',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-memory',
    summary: 'Persistent knowledge graph memory across agent sessions.',
    authLabel: 'local store',
    setupHint: 'Treat stored memories as tenant data and keep writes scoped.',
    tools: ['create_entities', 'add_observations', 'search_nodes'],
    tags: ['memory', 'local'],
    approval: 'L1 data',
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking MCP',
    category: 'core',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-sequential-thinking',
    summary: 'Structured step-by-step reasoning for planning and hard debugging.',
    authLabel: 'no token',
    setupHint: 'Best for planning; it should not perform external actions directly.',
    tools: ['think', 'revise', 'branch'],
    tags: ['reasoning', 'planning'],
    approval: 'L0 read',
  },
  {
    id: 'git',
    name: 'Git MCP',
    category: 'code',
    transport: 'stdio',
    endpoint: 'uvx mcp-server-git',
    summary: 'Inspect commits, diffs, branches and repository history.',
    authLabel: 'local repo',
    setupHint: 'Repository mutations should follow the same git review flow as EVA.',
    tools: ['status', 'diff', 'log'],
    tags: ['code', 'local'],
    approval: 'L1 writes',
  },
  {
    id: 'github',
    name: 'GitHub MCP',
    category: 'code',
    transport: 'http',
    endpoint: 'https://api.githubcopilot.com/mcp/',
    summary: 'Repository search, issues, pull requests and org metadata.',
    authLabel: 'OAuth or bearer token',
    secretLabel: 'GitHub MCP token',
    secretPlaceholder: 'Token optional until OAuth is wired',
    setupHint: 'Write actions still need the agent approval path before execution.',
    tools: ['search_repositories', 'create_issue', 'merge_pr'],
    tags: ['code', 'remote'],
    approval: 'L2 writes',
  },
  {
    id: 'gitlab',
    name: 'GitLab MCP',
    category: 'code',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-gitlab',
    summary: 'Project, merge request, issue and file operations for GitLab.',
    authLabel: 'GitLab token',
    secretLabel: 'GitLab personal access token',
    secretPlaceholder: 'glpat-...',
    setupHint: 'Set GITLAB_API_URL on the runner for self-hosted GitLab.',
    tools: ['projects', 'issues', 'merge_requests'],
    tags: ['code', 'remote'],
    approval: 'L2 writes',
  },
  {
    id: 'context7',
    name: 'Context7 MCP',
    category: 'code',
    transport: 'stdio',
    endpoint: 'npx -y @upstash/context7-mcp@latest',
    summary: 'Version-aware library docs and code examples at prompt time.',
    authLabel: 'no token',
    setupHint: 'Use before implementing library-specific code or migrations.',
    tools: ['resolve_library', 'get_docs', 'examples'],
    tags: ['docs', 'code'],
    approval: 'L0 read',
  },
  {
    id: 'playwright',
    name: 'Playwright MCP',
    category: 'web',
    transport: 'stdio',
    endpoint: 'npx @playwright/mcp@latest',
    summary: 'Browser automation through structured page accessibility snapshots.',
    authLabel: 'local browser',
    setupHint: 'Browser actions that touch accounts or production data need approvals.',
    tools: ['navigate', 'click', 'snapshot'],
    tags: ['browser', 'test'],
    approval: 'L2 web',
  },
  {
    id: 'brave-search',
    name: 'Brave Search MCP',
    category: 'web',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-brave-search',
    summary: 'Web, news and local search using the Brave Search API.',
    authLabel: 'Brave API key',
    secretLabel: 'Brave Search API key',
    secretPlaceholder: 'BSA...',
    setupHint: 'Store the API key in the encrypted MCP auth field or runner env.',
    tools: ['web_search', 'local_search', 'news'],
    tags: ['search', 'web'],
    approval: 'L0 read',
  },
  {
    id: 'exa',
    name: 'Exa MCP',
    category: 'web',
    transport: 'stdio',
    endpoint: 'npx exa-mcp-server',
    summary: 'Neural web search and research retrieval for agent workflows.',
    authLabel: 'Exa API key',
    secretLabel: 'Exa API key',
    secretPlaceholder: 'exa_...',
    setupHint: 'Use for research tasks; summarize sources before storing memory.',
    tools: ['search', 'research', 'contents'],
    tags: ['search', 'research'],
    approval: 'L0 read',
  },
  {
    id: 'tavily',
    name: 'Tavily MCP',
    category: 'web',
    transport: 'stdio',
    endpoint: 'npx -y tavily-mcp',
    summary: 'Search and extraction tuned for AI research agents.',
    authLabel: 'Tavily API key',
    secretLabel: 'Tavily API key',
    secretPlaceholder: 'tvly-...',
    setupHint: 'Use for live web answers; avoid writing scraped data without approval.',
    tools: ['search', 'extract', 'crawl'],
    tags: ['search', 'research'],
    approval: 'L0 read',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl MCP',
    category: 'web',
    transport: 'stdio',
    endpoint: 'npx -y firecrawl-mcp',
    summary: 'Crawl, scrape and map websites into structured content.',
    authLabel: 'Firecrawl API key',
    secretLabel: 'Firecrawl API key',
    secretPlaceholder: 'fc-...',
    setupHint: 'Respect robots, rate limits and data handling approval boundaries.',
    tools: ['scrape', 'crawl', 'map_site'],
    tags: ['scraping', 'web'],
    approval: 'L1 data',
  },
  {
    id: 'supabase',
    name: 'Supabase MCP',
    category: 'data',
    transport: 'http',
    endpoint: 'https://mcp.supabase.com/mcp',
    summary: 'Project inventory, SQL inspection and migration workflows.',
    authLabel: 'Supabase access token',
    secretLabel: 'Supabase MCP token',
    secretPlaceholder: 'Access token optional',
    setupHint: 'SQL and migration tools should stay behind high-approval actions.',
    tools: ['list_projects', 'execute_sql', 'apply_migration'],
    tags: ['database', 'remote'],
    approval: 'L3 data',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL MCP',
    category: 'data',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-postgres "$DATABASE_URL"',
    summary: 'Read-only schema inspection and SQL access for PostgreSQL.',
    authLabel: 'database URL',
    setupHint: 'Set DATABASE_URL on the runner with a least-privilege read-only role.',
    tools: ['list_tables', 'describe_table', 'query'],
    tags: ['database', 'sql'],
    approval: 'L2 data',
  },
  {
    id: 'redis',
    name: 'Redis MCP',
    category: 'data',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-redis "$REDIS_URL"',
    summary: 'Inspect Redis keys, streams and cached runtime state.',
    authLabel: 'Redis URL',
    setupHint: 'Set REDIS_URL on the runner and avoid broad production key scans without approval.',
    tools: ['keys', 'get', 'stream_read'],
    tags: ['database', 'cache'],
    approval: 'L2 data',
  },
  {
    id: 'google-drive',
    name: 'Google Drive MCP',
    category: 'productivity',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-gdrive',
    summary: 'Search, list and read files from Google Drive.',
    authLabel: 'Google OAuth file',
    setupHint: 'Runner needs a GDRIVE_CREDENTIALS_PATH with scoped OAuth credentials.',
    tools: ['search_files', 'read_file', 'list_files'],
    tags: ['docs', 'files'],
    approval: 'L1 data',
  },
  {
    id: 'slack',
    name: 'Slack MCP',
    category: 'productivity',
    transport: 'stdio',
    endpoint: 'npx -y @modelcontextprotocol/server-slack',
    summary: 'Read channels, send messages and coordinate team workflows.',
    authLabel: 'Slack bot token',
    secretLabel: 'Slack bot token',
    secretPlaceholder: 'xoxb-...',
    setupHint: 'Sending messages should remain an approval-gated action.',
    tools: ['channels', 'history', 'send_message'],
    tags: ['chat', 'team'],
    approval: 'L2 comms',
  },
  {
    id: 'linear',
    name: 'Linear MCP',
    category: 'productivity',
    transport: 'sse',
    endpoint: 'https://mcp.linear.app/sse',
    summary: 'Find, create and update Linear issues, projects and comments.',
    authLabel: 'OAuth',
    setupHint: 'Use approval for creating or changing roadmap and issue state.',
    tools: ['issues', 'projects', 'comments'],
    tags: ['planning', 'issues'],
    approval: 'L1 writes',
  },
  {
    id: 'notion',
    name: 'Notion MCP',
    category: 'productivity',
    transport: 'stdio',
    endpoint: 'npx -y @notionhq/notion-mcp-server',
    summary: 'Read and update Notion pages, databases and workspace content.',
    authLabel: 'Notion token',
    secretLabel: 'Notion integration token',
    secretPlaceholder: 'ntn_...',
    setupHint: 'Only connect workspaces and pages approved for the org.',
    tools: ['pages', 'databases', 'blocks'],
    tags: ['docs', 'workspace'],
    approval: 'L2 data',
  },
  {
    id: 'airtable',
    name: 'Airtable MCP',
    category: 'productivity',
    transport: 'stdio',
    endpoint: 'npx -y airtable-mcp-server',
    summary: 'Inspect bases, read records and update operational tables.',
    authLabel: 'Airtable API key',
    secretLabel: 'Airtable API key',
    secretPlaceholder: 'pat...',
    setupHint: 'Writes to business records should be approval-gated.',
    tools: ['bases', 'tables', 'records'],
    tags: ['database', 'workspace'],
    approval: 'L2 data',
  },
  {
    id: 'sentry',
    name: 'Sentry MCP',
    category: 'ops',
    transport: 'sse',
    endpoint: 'https://mcp.sentry.dev/sse',
    summary: 'Investigate issues, stack traces, releases and error trends.',
    authLabel: 'OAuth',
    setupHint: 'Keep issue comments and release changes behind approvals.',
    tools: ['issues', 'events', 'releases'],
    tags: ['observability', 'errors'],
    approval: 'L1 read',
  },
  {
    id: 'grafana',
    name: 'Grafana MCP',
    category: 'ops',
    transport: 'stdio',
    endpoint: 'docker run --rm -p 8000:8000 -e GRAFANA_URL -e GRAFANA_API_KEY mcp/grafana',
    summary: 'Dashboards, metrics and observability queries through Grafana.',
    authLabel: 'Grafana token',
    secretLabel: 'Grafana service account token',
    secretPlaceholder: 'glsa_...',
    setupHint: 'Use read-only service accounts for diagnostics.',
    tools: ['dashboards', 'datasources', 'query'],
    tags: ['observability', 'metrics'],
    approval: 'L1 read',
  },
  {
    id: 'aws',
    name: 'AWS MCP',
    category: 'ops',
    transport: 'stdio',
    endpoint: 'npx -y aws-mcp',
    summary: 'Cloud inventory, cost visibility and guarded AWS operations.',
    authLabel: 'AWS env or role',
    setupHint: 'Production cloud mutations must go through approvals.',
    tools: ['cost_explorer', 'list_resources', 'aws_api'],
    tags: ['cloud', 'infra'],
    approval: 'L3 prod',
  },
  {
    id: 'heroku',
    name: 'Heroku MCP',
    category: 'ops',
    transport: 'stdio',
    endpoint: 'npx -y @heroku/mcp-server',
    summary: 'Inspect and manage Heroku apps, config, builds and releases.',
    authLabel: 'Heroku API key',
    secretLabel: 'Heroku API key',
    secretPlaceholder: 'HEROKU_API_KEY',
    setupHint: 'Config var and deploy actions need production approval.',
    tools: ['apps', 'releases', 'config'],
    tags: ['cloud', 'deploy'],
    approval: 'L3 prod',
  },
  {
    id: 'stripe',
    name: 'Stripe MCP',
    category: 'commerce',
    transport: 'stdio',
    endpoint: 'npx -y @stripe/mcp --tools=all',
    summary: 'Customers, payments, subscriptions and billing operations.',
    authLabel: 'Stripe secret key',
    secretLabel: 'Stripe secret key',
    secretPlaceholder: 'sk_...',
    setupHint: 'Money-moving actions must use the Approval Engine.',
    tools: ['customers', 'payments', 'subscriptions'],
    tags: ['payments', 'billing'],
    approval: 'L3 money',
  },
  {
    id: 'shopify-dev',
    name: 'Shopify Dev MCP',
    category: 'commerce',
    transport: 'stdio',
    endpoint: 'npx -y @shopify/dev-mcp@latest',
    summary: 'Shopify app development docs, APIs and store tooling.',
    authLabel: 'Shopify auth',
    setupHint: 'Store mutations should remain approval-gated.',
    tools: ['admin_api', 'docs', 'storefront'],
    tags: ['commerce', 'docs'],
    approval: 'L2 writes',
  },
  {
    id: 'e2b',
    name: 'E2B Code Interpreter MCP',
    category: 'sandbox',
    transport: 'stdio',
    endpoint: 'npx -y @e2b/mcp-server',
    summary: 'Run code in isolated cloud sandboxes for analysis and tooling.',
    authLabel: 'E2B API key',
    secretLabel: 'E2B API key',
    secretPlaceholder: 'e2b_...',
    setupHint: 'Never pass secrets or customer data into sandbox code without approval.',
    tools: ['run_code', 'files', 'sandbox'],
    tags: ['code', 'sandbox'],
    approval: 'L2 code',
  },
  {
    id: 'pydantic-run-python',
    name: 'Pydantic Run Python MCP',
    category: 'sandbox',
    transport: 'stdio',
    endpoint: 'deno run -N -R=node_modules -W=node_modules --node-modules-dir=auto jsr:@pydantic/mcp-run-python stdio',
    summary: 'Run Python in a Pyodide sandbox for local analysis tasks.',
    authLabel: 'no token',
    setupHint: 'Use for computation and parsing; avoid side effects by design.',
    tools: ['run_python', 'inspect_result', 'artifacts'],
    tags: ['python', 'sandbox'],
    approval: 'L1 code',
  },
  {
    id: 'jetbrains',
    name: 'JetBrains MCP',
    category: 'code',
    transport: 'stdio',
    endpoint: 'npx -y @jetbrains/mcp-proxy',
    summary: 'Proxy agent requests into a local JetBrains IDE session.',
    authLabel: 'local IDE',
    setupHint: 'Best for developer-in-the-loop local coding sessions.',
    tools: ['ide_context', 'open_file', 'inspect_project'],
    tags: ['ide', 'code'],
    approval: 'L1 local',
  },
] satisfies McpCatalogItem[];
